Fix issues found by shellcheck
cekrem/create-elm-live-app pull request #1
Opened 2022-06-22 11:30 UTC by aitap

When you have to write shell scripts, [use a linter](https://www.shellcheck.net/).

 - Variables should be quoted to prevent word splitting.
 - When variable expansion is desired, use double quotes, not single quotes.

I'm not sure about quoting in the `project_dir="$1"` assignment, but when it comes to POSIX shell and quoting, it's better to be safe now than to chase obscure bugs later.

2022-06-28 08:36 UTC, cekrem approved these changes
You're of course right. I made this in `vim` without spellcheck set up, and quite quickly at that. 

Thanks for your contribution!

2022-06-28 08:37 UTC, cekrem requested changes
If you bump the version number in package.json as well, I'll merge 👍

2022-07-26 16:58 UTC, aitap commented
Sorry for disappearing for a while; I've bumped the version number now.

2022-08-03 10:51 UTC, cekrem approved these changes
LGTM

(btw, I was on holiday myself, so slow replies all around)

2022-08-03 10:52 UTC, merged